# Generated by Django 4.1.5 on 2023-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_auto_20200712_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent',
            name='album',
            field=models.CharField(default='album', max_length=200),
        ),
        migrations.AddField(
            model_name='recent',
            name='singer',
            field=models.CharField(default='singer', max_length=200),
        ),
    ]
